### ISSUE TITLE
Hides npcs 

### ISSUE THREAD

**Issue by Grass69z** [hiisuuii/personal-space#1]
Great mod but when I get close too npcs like the bazaar or hub selector they also disappear if this is possible to fix please do so

**Comment by hiisuuii** [comment]
Not really possible to fix. NPCs are just fake players, but the client thinks they're as real as any other player. Sorry

**Comment by Grass69z** [comment]
I know it would be some work but could you implement a blacklist feature so we could remove npcs from being hidden I don't quite know how to find the npc name so maybe you could have keybind like while holding alt + right click to add that player to a blacklist that doesn't allow them to be hidden

**Comment by hiisuuii** [comment]
> I know it would be some work but could you implement a blacklist feature so we could remove npcs from being hidden I don't quite know how to find the npc name so maybe you could have keybind like while holding alt + right click to add that player to a blacklist that doesn't allow them to be hidden 

That MIGHT be possible. I think it'll depend on how most NPC plugins work, but I'll look into it

**Comment by hiisuuii** [comment]
I've had another look at this and determined that in pretty much all cases it is completely impossible. There's no way to tell the difference between a real person and an NPC from the game's perspective unfortunately.
