### ISSUE TITLE
Center of players is at the bottom of the model

### ISSUE THREAD

**Issue by ItsPasi** [hiisuuii/personal-space#2]
At low distance settings this makes players only disappear if you look at the legs or only hides them while sneaking. Would there be a way to make it uniform across the player model? Or just making the center at the middle of the model would already be a great improvement.

**Comment by hiisuuii** [comment]
I'll see about this. I'm working on an update to make armor and capes fade out as well (harder than it sounds) so this will probably be in with that as well.
